# Dev Profile

# Security (Optional)
# spring.security.user.name=${ADMIN_USER}
# spring.security.user.password=${ADMIN_PASS}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*

# Alternative CORS
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:4200,https://elearn-ui.onrender.com
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
# spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=false

# Services
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=https://elearn-user-service.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=https://elearn-course-service.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/courses/**

spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=https://elearn-notification-service.onrender.com
spring.cloud.gateway.routes[2].predicates[0]=Path=/notifications/**

spring.cloud.gateway.routes[3].id=purchase-service
spring.cloud.gateway.routes[3].uri=https://elearn-purchase-service.onrender.com
spring.cloud.gateway.routes[3].predicates[0]=Path=/purchase-history/**

spring.cloud.gateway.routes[4].id=review-service
spring.cloud.gateway.routes[4].uri=https://elearn-review-service.onrender.com
spring.cloud.gateway.routes[4].predicates[0]=Path=/reviews/**

# Swagger Routes
spring.cloud.gateway.routes[5].id=user-service-docs
spring.cloud.gateway.routes[5].uri=https://elearn-user-service.onrender.com
spring.cloud.gateway.routes[5].predicates[0]=Path=/user-service/v3/api-docs
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/user-service/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[6].id=course-service-docs
spring.cloud.gateway.routes[6].uri=https://elearn-course-service.onrender.com
spring.cloud.gateway.routes[6].predicates[0]=Path=/course-service/v3/api-docs
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/course-service/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[7].id=notification-service-docs
spring.cloud.gateway.routes[7].uri=https://elearn-notification-service.onrender.com
spring.cloud.gateway.routes[7].predicates[0]=Path=/notification-service/v3/api-docs
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/notification-service/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[8].id=purchase-service-docs
spring.cloud.gateway.routes[8].uri=https://elearn-purchase-service.onrender.com
spring.cloud.gateway.routes[8].predicates[0]=Path=/purchase-service/v3/api-docs
spring.cloud.gateway.routes[8].filters[0]=RewritePath=/purchase-service/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[9].id=review-service-docs
spring.cloud.gateway.routes[9].uri=https://elearn-review-service.onrender.com
spring.cloud.gateway.routes[9].predicates[0]=Path=/review-service/v3/api-docs
spring.cloud.gateway.routes[9].filters[0]=RewritePath=/review-service/(?<segment>.*), /${segment}